# Generated by Django 4.2.3 on 2023-07-12 09:10

import apps.musica.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileMusic', models.FileField(upload_to=apps.musica.models.get_file_path)),
                ('name', models.CharField(max_length=100)),
                ('track_number', models.IntegerField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_related', to='musica.autor')),
                ('colaborators', models.ManyToManyField(blank=True, related_name='colaborators_set', to='musica.autor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.genero')),
            ],
        ),
    ]
